{{- if .Values.secrets }}
{{- range $s := .Values.secrets }}
{{- if $s.data }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $s.name }}
  labels:
    chart: {{ template "cronjob.chart" $ }}
    heritage: {{ $.Release.Service }}
    release: {{ $.Release.Name }}
    app: {{ template "cronjob.name" $ }}
data:
{{ toYaml $s.data | indent 2 }}
{{- end }}
{{- end }}
{{- end }}
