{{- if .Values.x509.enabled }}
apiVersion: v1
kind: Service
metadata:
  labels:
    app: spin
    cluster: spin-gate
  name: spin-gate-x509
  annotations:
{{ toYaml .Values.x509.service.annotations | indent 4 }}
spec:
  externalTrafficPolicy: Cluster
  {{- if .Values.x509.service.loadBalancerIP }}
  loadBalancerIP: {{ .Values.x509.service.loadBalancerIP }}
  {{- end }}
  {{- if .Values.x509.service.clusterIP }}
  clusterIP: {{ .Values.x509.service.clusterIP }}
  {{- end }}
  ports:
  - port: 443
    protocol: TCP
    targetPort: {{ .Values.x509.service.targetPort }}
  selector:
    app: spin
    cluster: spin-gate
  sessionAffinity: None
  type: {{ .Values.x509.service.type }}
{{- end }}
